
import React from 'react'
import Hero from './Hero'
import Image from 'next/image'
import Link from 'next/link'
import BelowHero from './BelowHero'
import OurApproach from './OurApproach'

const HomePage = () => {
    return (
        <div className="flex flex-col items-center">
            <Hero />
            <div className="mt-14 px-4 sm:px-8 md:px-16 lg:px-32 xl:px-64 text-center">
                <div className="text-center text-3xl">Enabling clients to cultivate greater economic and societal returns in the built environment</div>
                <div className="text-left mt-12 text-xl">Real estate is fundamental to the human experience. It's where the world spends 90 percent of its time living, working, shopping, and playing. But society's needs, expectations, and wants of real estate have permanently evolved, driven by the COVID-19 pandemic, climate change, and increasing economic uncertainty.
                    <br />
                    <div className='mt-10'>
                        McKinsey's Real Estate Practice works with investors, property owners, real estate managers, and the world's leading organizations who are the primary occupiers and users of space to lean into these disruptions and accelerate sustainable and inclusive growth that benefit the businesses, environments, and communities they serve.
                    </div>
                    <div className='mt-10'>
                        With proprietary technology, global scale, and local expertise, we are uniquely equipped to embolden clients to embrace disruption, pioneer innovation, and shape a new future for themselves and for the industry.
                    </div>
                </div>
            </div>
            <div className="flex flex-col md:flex-row md:space-x-4 space-y-4 md:space-y-0 mt-20">
                <div className="flex-1 bg-white rounded-lg px-6 py-8 m-2  text-center">
                    <div className="text-7xl font-bold text-blue-700">~20%</div>
                    <div className="text-xl mt-4">of global GDP</div>
                    <div className="text-gray-700">is generated by real estate</div>
                </div>
                <div className="hidden md:block md:w-px md:bg-gray-400"></div>
                <div className="flex-1 bg-white rounded-lg px-6 py-8 m-2  text-center">
                    <div className="text-7xl font-bold text-blue-700 "> {`>39%`} </div>
                    <div className="text-xl mt-4">of global greenhouse emissions</div>
                    <div className="text-gray-700">are generated from the real estate industry </div>
                </div>
                <div className="hidden md:block md:w-px md:bg-gray-400"></div>
                <div className="flex-1 bg-white rounded-lg px-6 py-8 m-2  text-center">
                    <div className="text-7xl font-bold text-blue-700">~$4 </div>
                    <div className="text-xl mt-4">trillion</div>
                    <div className="text-gray-700">is spent on rent by organizations annually</div>
                </div>
            </div>

            
            <BelowHero />  
            
            <OurApproach />
            
        </div>

    )
}

export default HomePage
